/* Styling (rustic / kraft-paper editorial) — carried over from the demo,
   extended with nav / manage-booking / admin styles. */

export const GLOBAL_CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=EB+Garamond:ital,wght@0,400;0,500;1,400&display=swap');
  .rustic-card { transition: transform .18s ease, box-shadow .18s ease; }
  .rustic-card:hover { transform: translateY(-3px); box-shadow: 0 10px 28px rgba(74,55,35,.16); }
  .rustic-submit { transition: transform .12s ease, background .2s ease; }
  .rustic-submit:hover { transform: translateY(-1px); }
  input::placeholder { color: #b3a48f; }
  .colophon-link { color: #a4562a; text-decoration: none; border-bottom: 1px solid rgba(164,86,42,.4); }
  .colophon-link:hover { border-bottom-color: #a4562a; }

  /* Two-column grids that collapse to one column on narrow screens. */
  .rustic-grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
  .rustic-trip-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  @media (max-width: 480px) {
    .rustic-grid-2, .rustic-trip-row { grid-template-columns: 1fr; }
  }
`;

const serif = "'Cormorant Garamond', Georgia, serif";
const body = "'EB Garamond', Georgia, serif";
const ink = "#4a3723";
const cream = "#f7f1e6";
const kraft = "#efe4d2";

export const S = {
  page: {
    minHeight: "100vh",
    background:
      "radial-gradient(1200px 600px at 50% -10%, #fbf6ec 0%, #f1e7d5 55%, #e9dcc6 100%)",
    padding: "32px 16px 48px",
    fontFamily: body,
    color: ink,
  },
  frame: {
    maxWidth: 620,
    margin: "0 auto",
    background: cream,
    border: "1px solid #ddceb4",
    borderRadius: 4,
    boxShadow: "0 20px 60px rgba(74,55,35,.14)",
    padding: "36px 30px 26px",
    position: "relative",
  },

  // top navigation between Book / Manage / Admin
  nav: {
    display: "flex",
    justifyContent: "center",
    gap: 6,
    marginBottom: 22,
    flexWrap: "wrap",
  },
  navBtn: {
    background: "none",
    border: "1px solid transparent",
    borderRadius: 999,
    padding: "6px 14px",
    cursor: "pointer",
    font: "inherit",
    fontSize: 14,
    color: "#9a7d55",
    fontStyle: "italic",
  },
  navBtnActive: {
    background: "#fffdf8",
    border: "1px solid #e0d0b5",
    color: ink,
    fontStyle: "normal",
  },

  header: { textAlign: "center", marginBottom: 26 },
  sprig: { fontSize: 26, color: "#a4562a", marginBottom: 6 },
  eyebrow: {
    fontFamily: body,
    fontStyle: "italic",
    letterSpacing: ".04em",
    color: "#9a7d55",
    margin: 0,
    fontSize: 15,
  },
  coupleNames: {
    fontFamily: serif,
    fontWeight: 700,
    fontSize: 27,
    lineHeight: 1.15,
    margin: "2px 0 2px",
    color: ink,
    letterSpacing: ".01em",
  },
  eventMeta: {
    fontFamily: body,
    fontStyle: "italic",
    fontSize: 15,
    color: "#8a7150",
    margin: "0 0 14px",
    letterSpacing: ".02em",
  },
  title: {
    fontFamily: serif,
    fontWeight: 700,
    fontSize: 38,
    lineHeight: 1.05,
    margin: "10px 0 10px",
    color: ink,
    letterSpacing: ".01em",
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 1.5,
    color: "#6b563d",
    maxWidth: 460,
    margin: "0 auto",
  },
  headerDate: {
    fontFamily: serif,
    fontSize: 17,
    color: "#a4562a",
    marginTop: 8,
    letterSpacing: ".02em",
  },

  stepLabel: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
    fontFamily: serif,
    fontSize: 21,
    fontWeight: 600,
    color: ink,
  },
  stepNum: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "#a4562a",
    color: cream,
    fontSize: 15,
    fontFamily: body,
    flexShrink: 0,
  },

  pointCard: {
    textAlign: "left",
    background: "#fffdf8",
    border: "1px solid #e0d0b5",
    borderRadius: 4,
    padding: "20px 18px",
    cursor: "pointer",
    color: ink,
    font: "inherit",
  },
  serviceIcon: { fontSize: 24, color: "#a4562a", marginBottom: 6, lineHeight: 1 },
  pointName: { fontFamily: serif, fontSize: 22, fontWeight: 700 },
  pointNote: { fontStyle: "italic", color: "#8a7150", fontSize: 15, marginTop: 2 },
  divider: { height: 1, background: "#e6d8bf", margin: "14px 0" },
  pointMeta: { fontSize: 14, color: "#6b563d" },
  chooseHint: { marginTop: 12, color: "#a4562a", fontSize: 15, fontFamily: serif },

  back: {
    background: "none",
    border: "none",
    color: "#9a7d55",
    cursor: "pointer",
    font: "inherit",
    fontSize: 15,
    padding: 0,
    marginBottom: 14,
    fontStyle: "italic",
  },
  vanList: { display: "flex", flexDirection: "column", gap: 16 },
  vanCard: {
    background: "#fffdf8",
    border: "1px solid #e0d0b5",
    borderRadius: 4,
    padding: "16px 16px 18px",
  },
  vanHead: { fontFamily: serif, fontSize: 22, fontWeight: 700, marginBottom: 12 },
  tripBtn: {
    background: cream,
    border: "1px solid #e0d0b5",
    borderRadius: 4,
    padding: "14px 12px",
    textAlign: "left",
    color: ink,
    font: "inherit",
  },
  tripLabel: { fontFamily: serif, fontSize: 18, fontWeight: 600 },
  tripTime: { fontSize: 14, color: "#6b563d", margin: "2px 0 10px" },
  seatBadge: {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 999,
    fontSize: 13,
    letterSpacing: ".02em",
  },

  summaryBox: {
    background: kraft,
    border: "1px dashed #cbb794",
    borderRadius: 4,
    padding: "14px 16px",
    marginBottom: 20,
    fontSize: 16,
  },
  summaryEyebrow: {
    fontFamily: serif,
    fontSize: 15,
    fontWeight: 600,
    color: "#a4562a",
    marginBottom: 4,
    letterSpacing: ".03em",
  },
  summaryNote: { fontStyle: "italic", color: "#8a7150" },
  summaryTrip: { marginTop: 4, color: "#6b563d" },
  summarySeats: { marginTop: 8, fontSize: 14, color: "#a4562a" },

  fieldLabel: {
    display: "block",
    fontSize: 15,
    color: "#6b563d",
    marginBottom: 6,
    fontStyle: "italic",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "11px 13px",
    border: "1px solid #d8c6a8",
    borderRadius: 4,
    background: "#fffdf8",
    font: "inherit",
    fontSize: 16,
    color: ink,
    marginBottom: 14,
    outline: "none",
  },
  nameRow: { display: "flex", gap: 8, alignItems: "center", marginBottom: 10 },
  removeBtn: {
    width: 38,
    height: 38,
    flexShrink: 0,
    border: "1px solid #d8c6a8",
    background: "#fffdf8",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 20,
    color: "#a4562a",
    lineHeight: 1,
  },
  addBtn: {
    background: "none",
    color: "#a4562a",
    borderRadius: 4,
    padding: "9px 14px",
    cursor: "pointer",
    font: "inherit",
    fontSize: 15,
    marginTop: 4,
    borderColor: "#cbb794",
    borderStyle: "dashed",
    borderWidth: 1,
  },
  error: {
    background: "#f6e4dc",
    border: "1px solid #dcae97",
    color: "#9c3d1c",
    padding: "10px 13px",
    borderRadius: 4,
    marginTop: 14,
    fontSize: 15,
  },
  submit: {
    width: "100%",
    marginTop: 20,
    padding: "14px",
    background: "#a4562a",
    color: cream,
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: serif,
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: ".02em",
  },

  checkMark: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    background: "#e4ead9",
    color: "#4f6135",
    fontSize: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "6px auto 14px",
  },
  doneTitle: { fontFamily: serif, fontSize: 34, fontWeight: 700, margin: "0 0 6px" },
  doneSub: { color: "#6b563d", fontSize: 16, marginBottom: 22 },
  ticket: {
    background: "#fffdf8",
    border: "1px solid #e0d0b5",
    borderRadius: 4,
    padding: "18px 20px",
    textAlign: "left",
    marginBottom: 20,
  },
  ticketRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    padding: "7px 0",
    fontSize: 16,
    color: "#6b563d",
  },
  ticketDivider: { height: 1, background: "#e6d8bf", margin: "8px 0" },
  refPill: {
    display: "inline-block",
    background: kraft,
    border: "1px dashed #cbb794",
    borderRadius: 4,
    padding: "6px 12px",
    fontFamily: serif,
    fontSize: 20,
    letterSpacing: ".08em",
    color: ink,
    marginBottom: 16,
  },

  // manage-booking + admin
  noteText: { fontSize: 15, color: "#6b563d", lineHeight: 1.5, marginBottom: 16 },
  boardingNote: {
    fontSize: 14,
    color: "#8a7150",
    fontStyle: "italic",
    lineHeight: 1.5,
    margin: "14px 0 0",
  },
  secondaryBtn: {
    background: "#fffdf8",
    color: ink,
    border: "1px solid #d8c6a8",
    borderRadius: 4,
    padding: "10px 16px",
    cursor: "pointer",
    font: "inherit",
    fontSize: 15,
  },
  dangerBtn: {
    background: "none",
    color: "#9c3d1c",
    border: "1px solid #dcae97",
    borderRadius: 4,
    padding: "8px 14px",
    cursor: "pointer",
    font: "inherit",
    fontSize: 14,
  },
  toolbar: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    marginBottom: 16,
    flexWrap: "wrap",
  },
  statRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    background: kraft,
    border: "1px dashed #cbb794",
    borderRadius: 4,
    padding: "12px 16px",
    marginBottom: 18,
    fontSize: 15,
  },
  runGroup: {
    background: "#fffdf8",
    border: "1px solid #e0d0b5",
    borderRadius: 4,
    padding: "14px 16px",
    marginBottom: 14,
  },
  runGroupHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 10,
    fontFamily: serif,
    fontSize: 19,
    fontWeight: 600,
  },
  bookingCard: {
    borderTop: "1px solid #eee0c9",
    padding: "12px 0 4px",
    fontSize: 15,
  },
  bookingHeadRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  meta: { fontSize: 14, color: "#8a7150", marginTop: 2 },
  emptyState: {
    textAlign: "center",
    color: "#8a7150",
    fontStyle: "italic",
    padding: "24px 0",
    fontSize: 15,
  },

  footer: { marginTop: 28, textAlign: "center" },
  footerRule: { height: 1, background: "#e6d8bf", margin: "0 auto 10px", maxWidth: 200 },
  footerText: { fontSize: 13, color: "#a99a83", fontStyle: "italic", margin: 0 },
  colophon: {
    fontSize: 13,
    color: "#8a7150",
    lineHeight: 1.6,
    margin: "12px auto 0",
    maxWidth: 400,
  },
  colophonBrand: { fontFamily: serif, fontWeight: 600, color: "#6b563d" },
};
